apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "sparrow-sidecar-injector"
webhooks:
- name: "sparrow.mesh.fp.net"
  rules:
  - apiGroups:   ["*"]
    apiVersions: ["*"]
    operations:  ["CREATE"]
    resources:   ["deployments"]
    scope:       "*"
  #matchPolicy: Exact
  namespaceSelector:
    matchLabels:
      sparrow-injection: enabled
  clientConfig:
    service:
      namespace: "sparrow-system"
      name: "sparrow-sidecar-injector-service"
      path: "/inject"
      port: 80
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lVSnkzRzhFS29aNlBFa0wzaUgzWFJlbFlTWHYwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1dERThNRG9HQTFVRUF3d3pjM0JoY25KdmR5MXphV1JsWTJGeUxXbHVhbVZqZEc5eUxYTmxjblpwWTJVdQpjM0JoY25KdmR5MXplWE4wWlcwdWMzWmpNUXN3Q1FZRFZRUUtEQUpHVURFTE1Ba0dBMVVFQmhNQ1FWVXdIaGNOCk1qQXdOakUzTURVMU5EUTVXaGNOTWpFd05qRTNNRFUxTkRRNVdqQllNVHd3T2dZRFZRUURERE56Y0dGeWNtOTMKTFhOcFpHVmpZWEl0YVc1cVpXTjBiM0l0YzJWeWRtbGpaUzV6Y0dGeWNtOTNMWE41YzNSbGJTNXpkbU14Q3pBSgpCZ05WQkFvTUFrWlFNUXN3Q1FZRFZRUUdFd0pCVlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQVBPaTczMURWVHo3L2czVXJPYmdMS2RZZDhmM1U2TSs1TlZvaFAwbDlSdzBiaUZ3OEJ0bkRhUmcKNDMrSWQvaGVCdSsxbDhFaWZIZnR1QVl1ZHZrNzU5YnNmenFUNmdBdUpORDBiZG9BZmZlMjVuSWovNmFtbzc1Rwp6OVpZOUhlek9wNzVzQ3hQODN2UnUzMCtGVXVDWE5FODF0RERGUFEzbWpWb01xOHIxOWFpU2dzM3pzRnJUODE0CjJKVWV6SGVnWWViMXRZKzlvMklYT1JoM0lYeEthYlA1ZlN3aHFidi8xcTZWVWJnT1A0MUM4bnBRRVd2WkZLOGgKT1B5TGt5MEkvZEtXRUpjcmxMQndtQ2hqalhUZjMvamcvWjlhT0Y0K2tvaXh5Z3Qwc0xNOUZydTU2WVFuL0d5RQpDaVlnL0lkTDBLTUdoZ0YwZndLZ0Y3Z2xYTENQeHRFQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZIWm9KNXU2ClMxdFRmNGkzNmNLQXhZRTJJbXFBTUI4R0ExVWRJd1FZTUJhQUZIWm9KNXU2UzF0VGY0aTM2Y0tBeFlFMkltcUEKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUw5OGh2amVtdFhUZFhIRApHYTdWZ2JPOFZlQWsyMXVjK2VvdG5jeDhPbXZpV3pweUE1NzZ1dmpiOGFueloxdmRCT1E0Sm5Rdm1oamhxVm5WCmRDWmp3REJHaXZOWVl0eEJtMlRBK2h6NGxzOEw1Q3FPL0xBV1phVUVSTklUendwcnduT1Zta1pQU0pOQTBGQjgKamc4UkpDNWpYOWRXRGVMRm5yWTNwWWxVN25KWWNkZWYzS3E4aVJHbXRMY0tSNGRjT3NyK2JjVmhrcnVoK0VmbQpOVVA2L0huU0Faa0gxbEdQVmp6d0NndXZJaU1KYkpLT0tDc3ZaWXdiMmUzanFQV0Z0TzF2SzJLdnR6SUtEUzlMCmxFejl6Y3hTSklwN2hqbnpwdFQwMXJ0NHRPRTQwZTd2WTJ3dXR6UVVwYnFGZXRaWVdTNzZnYUM4T0FLZkM0OEYKMjZhU2VBOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "sparrow-sidecar-validator"
webhooks:
- name: "sparrow.mesh.fp.net"
  rules:
  - apiGroups:   ["*"]
    apiVersions: ["*"]
    operations:  ["CREATE"]
    resources:   ["deployments"]
    scope:       "*"
  #matchPolicy: Exact
  namespaceSelector:
    matchLabels:
      sparrow-injection: enabled
  clientConfig:
    service:
      namespace: "sparrow-system"
      name: "sparrow-sidecar-injector-service"
      path: "/validate"
      port: 80
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lVSnkzRzhFS29aNlBFa0wzaUgzWFJlbFlTWHYwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1dERThNRG9HQTFVRUF3d3pjM0JoY25KdmR5MXphV1JsWTJGeUxXbHVhbVZqZEc5eUxYTmxjblpwWTJVdQpjM0JoY25KdmR5MXplWE4wWlcwdWMzWmpNUXN3Q1FZRFZRUUtEQUpHVURFTE1Ba0dBMVVFQmhNQ1FWVXdIaGNOCk1qQXdOakUzTURVMU5EUTVXaGNOTWpFd05qRTNNRFUxTkRRNVdqQllNVHd3T2dZRFZRUURERE56Y0dGeWNtOTMKTFhOcFpHVmpZWEl0YVc1cVpXTjBiM0l0YzJWeWRtbGpaUzV6Y0dGeWNtOTNMWE41YzNSbGJTNXpkbU14Q3pBSgpCZ05WQkFvTUFrWlFNUXN3Q1FZRFZRUUdFd0pCVlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQVBPaTczMURWVHo3L2czVXJPYmdMS2RZZDhmM1U2TSs1TlZvaFAwbDlSdzBiaUZ3OEJ0bkRhUmcKNDMrSWQvaGVCdSsxbDhFaWZIZnR1QVl1ZHZrNzU5YnNmenFUNmdBdUpORDBiZG9BZmZlMjVuSWovNmFtbzc1Rwp6OVpZOUhlek9wNzVzQ3hQODN2UnUzMCtGVXVDWE5FODF0RERGUFEzbWpWb01xOHIxOWFpU2dzM3pzRnJUODE0CjJKVWV6SGVnWWViMXRZKzlvMklYT1JoM0lYeEthYlA1ZlN3aHFidi8xcTZWVWJnT1A0MUM4bnBRRVd2WkZLOGgKT1B5TGt5MEkvZEtXRUpjcmxMQndtQ2hqalhUZjMvamcvWjlhT0Y0K2tvaXh5Z3Qwc0xNOUZydTU2WVFuL0d5RQpDaVlnL0lkTDBLTUdoZ0YwZndLZ0Y3Z2xYTENQeHRFQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZIWm9KNXU2ClMxdFRmNGkzNmNLQXhZRTJJbXFBTUI4R0ExVWRJd1FZTUJhQUZIWm9KNXU2UzF0VGY0aTM2Y0tBeFlFMkltcUEKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUw5OGh2amVtdFhUZFhIRApHYTdWZ2JPOFZlQWsyMXVjK2VvdG5jeDhPbXZpV3pweUE1NzZ1dmpiOGFueloxdmRCT1E0Sm5Rdm1oamhxVm5WCmRDWmp3REJHaXZOWVl0eEJtMlRBK2h6NGxzOEw1Q3FPL0xBV1phVUVSTklUendwcnduT1Zta1pQU0pOQTBGQjgKamc4UkpDNWpYOWRXRGVMRm5yWTNwWWxVN25KWWNkZWYzS3E4aVJHbXRMY0tSNGRjT3NyK2JjVmhrcnVoK0VmbQpOVVA2L0huU0Faa0gxbEdQVmp6d0NndXZJaU1KYkpLT0tDc3ZaWXdiMmUzanFQV0Z0TzF2SzJLdnR6SUtEUzlMCmxFejl6Y3hTSklwN2hqbnpwdFQwMXJ0NHRPRTQwZTd2WTJ3dXR6UVVwYnFGZXRaWVdTNzZnYUM4T0FLZkM0OEYKMjZhU2VBOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: sparrow-system
  labels:
    sparrow-injection: enabled
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sparrow-sidecar-injector-service
  namespace: sparrow-system
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sparrow-sidecar-injector-service
  namespace: sparrow-system
subsets:
  - addresses:
      - ip: 172.16.2.3 #your sidecar injector service address
    ports:
      - port: 6001

